import { useQuery } from 'react-query';
import Head from 'next/head';
import { getMovies } from '@/apiRequests/moviesRequest';

import MoviesGrid from '@/components/MoviesGrid';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <MoviesGrid />
      </main>
    </>
  );
}
