import Head from 'next/head';
import MoviesGrid from '@/components/MoviesSection';
import TvShowsGrid from '@/components/TvShowsSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <MoviesGrid />

        <TvShowsGrid />
      </main>
    </>
  );
}
